team_keys = {
    "Arizona": "ARI",
    "Atlanta": "ATL",
    "Baltimore": "BAL",
    "Boston": "BOS",
    "Chi. Cubs": "CHC",
    "Chi. White Sox": "CHW",
    "Cincinnati": "CIN",
    "Cleveland": "CLE",
    "Colorado": "COL",
    "Detroit": "DET",
    "Houston": "HOU",
    "Kansas City": "KC",
    "L.A. Angels": "LAA",
    "L.A. Dodgers": "LAD",
    "Milwaukee": "MIL",
    "Minnesota": "MIN",
    "Miami": "MIA",
    "N.Y. Mets": "NYM",
    "N.Y. Yankees": "NYY",
    "Oakland": "OAK",
    "Philadelphia": "PHI",
    "Pittsburgh": "PIT",
    "St. Louis": "STL",
    "San Diego": "SDP",
    "San Francisco": "SFG",
    "Seattle": "SEA",
    "Tampa Bay": "TBR",
    "Texas": "TEX",
    "Toronto": "TOR",
    "Washington": "WSN",
}
